In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(
    "../data/interim/cleaned_data.csv",
    parse_dates=["InvoiceDate"]
)

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom

In [3]:
print(df.shape)

df.info()

(779425, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 779425 entries, 0 to 779424
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      779425 non-null  int64
 1   StockCode    779425 non-null  object
 2   Description  779425 non-null  object
 3   Quantity     779425 non-null  int64
 4   InvoiceDate  779425 non-null  datetime64[ns]
 5   Price        779425 non-null  float64
 6   Customer ID  779425 non-null  int64
 7   Country      779425 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(3), object(3)
memory usage: 47.6+ MB

### Revenue

This feature will be used for sales analysis, customer value estimation, forecasting, and inventory optimization.

In [4]:
df["Revenue"] = df["Quantity"] * df["Price"]

df[["Quantity","Price","Revenue"]].head()

   Quantity  Price  Revenue
0        12   6.95     83.4
1        12   6.75     81.0
2        12   6.75     81.0
3        48   2.10    100.8
4        24   1.25     30.0

### Time-based Features

Time-related features are extracted from the InvoiceDate column to analyze purchasing behavior over different time periods.

In [5]:
df["Year"] = df["InvoiceDate"].dt.year

df["Month"] = df["InvoiceDate"].dt.month

df["MonthName"] = df["InvoiceDate"].dt.month_name()

df["Day"] = df["InvoiceDate"].dt.day

df["DayOfWeek"] = df["InvoiceDate"].dt.day_name()

df["Hour"] = df["InvoiceDate"].dt.hour

df["Quarter"] = df["InvoiceDate"].dt.quarter

### Weekend Indicator Feature

In [6]:
df["IsWeekend"] = (
    df["DayOfWeek"]
    .isin(["Saturday", "Sunday"])
    .astype(int)
)

df[["DayOfWeek","IsWeekend"]].head()

  DayOfWeek  IsWeekend
0   Tuesday          0
1   Tuesday          0
2   Tuesday          0
3   Tuesday          0
4   Tuesday          0

### Basket Size

Basket Size represents the total number of items purchased within a single invoice.

In [7]:
basket_size = (
    df.groupby("Invoice")["Quantity"]
    .sum()
)

df["BasketSize"] = df["Invoice"].map(basket_size)

df[["Invoice","BasketSize"]].head()

   Invoice  BasketSize
0   489434         166
1   489434         166
2   489434         166
3   489434         166
4   489434         166

### Order Value

In [8]:
order_value = (
    df.groupby("Invoice")["Revenue"]
    .sum()
)

df["OrderValue"] = df["Invoice"].map(order_value)

df[["Invoice","OrderValue"]].head()

   Invoice  OrderValue
0   489434       505.3
1   489434       505.3
2   489434       505.3
3   489434       505.3
4   489434       505.3

In [9]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,Year,Month,MonthName,Day,DayOfWeek,Hour,Quarter,IsWeekend,BasketSize,OrderValue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4,2009,12,December,1,Tuesday,7,4,0,166,505.3
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0,2009,12,December,1,Tuesday,7,4,0,166,505.3
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0,2009,12,December,1,Tuesday,7,4,0,166,505.3
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8,2009,12,December,1,Tuesday,7,4,0,166,505.3
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0,2009,12,December,1,Tuesday,7,4,0,166,505.3

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 779425 entries, 0 to 779424
Data columns (total 19 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      779425 non-null  int64
 1   StockCode    779425 non-null  object
 2   Description  779425 non-null  object
 3   Quantity     779425 non-null  int64
 4   InvoiceDate  779425 non-null  datetime64[ns]
 5   Price        779425 non-null  float64
 6   Customer ID  779425 non-null  int64
 7   Country      779425 non-null  object
 8   Revenue      779425 non-null  float64
 9   Year         779425 non-null  int32
 10  Month        779425 non-null  int32
 11  MonthName    779425 non-null  object
 12  Day          779425 non-null  int32
 13  DayOfWeek    779425 non-null  object
 14  Hour         779425 non-null  int32
 15  Quarter      779425 non-null  int32
 16  IsWeekend    779425 non-null  int64
 17  BasketSize   779425 non-null  int64
 18  OrderValue   779425 non-null  float64
dtypes: datetime64[ns](1), float64(3), int32(5), int64(5), object(5)
memory usage: 98.1+ MB

In [11]:
df.to_csv(
    "../data/processed/feature_engineered_data.csv",
    index=False
)

print("Feature engineered dataset saved successfully.")

Feature engineered dataset saved successfully.

## Summary

✔ Loaded the cleaned dataset for feature engineering.

✔ Created new features including Revenue, time-based attributes, weekend indicator, Basket Size, and Order Value.

✔ Verified the newly generated features for consistency and completeness.

✔ Saved the feature-engineered dataset for downstream machine learning and analytics tasks.

**Output File:**

`data/processed/feature_engineered_data.csv`

The generated features will be used for customer segmentation, demand forecasting, churn prediction, inventory optimization, and dashboard development.